services:
  - type: web
    name: fastapi-logistics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: Logistics
          property: connectionString
      - key: EXPIRES_IN
        value: 30
      - key: FACE_API_KEY
        sync: false
      - key: FACE_API_URL
        sync: false
    autoDeploy: true

databases:
  - name: logistics-db
    plan: free
    databaseName: neondb
    user: neondb_owner