services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: neondb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: EXPIRES_IN
        value: 30
      - key: FACE_API_KEY
        sync: false
      - key: FACE_API_URL
        sync: false